<?xml version="1.0" standalone="yes"?><!DOCTYPE wcregion [
	<!ELEMENT wcregion (rid, error, rname, region_wordcount, max, min, stddev, average, count, donations, numdonors)>
	<!ELEMENT rid (#PCDATA)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT rname (#PCDATA)>
	<!ELEMENT region_wordcount (#PCDATA)>
	<!ELEMENT max (#PCDATA)>
	<!ELEMENT min (#PCDATA)>
	<!ELEMENT stddev (#PCDATA)>
	<!ELEMENT average (#PCDATA)>
	<!ELEMENT count (#PCDATA)>
	<!ELEMENT donations (#PCDATA)>
	<!ELEMENT numdonors (#PCDATA)>
]>
<wcregion>
<rid>84</rid>
<rname>United States :: Washington :: Seattle</rname>
<region_wordcount>25865208</region_wordcount>
<max>310458</max>
<min>1</min>
<stddev>0</stddev>
<average>31736</average>
<count>815</count>
<donations>7735.00</donations>
<numdonors>148</numdonors>
</wcregion>
