<?xml version="1.0" standalone="yes"?><!DOCTYPE wcstats [
	<!ELEMENT wcstats (error, site_wordcount, wordcounts)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT site_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc, wcdate, max, min, stddev, average, count)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
	<!ELEMENT max (#PCDATA)>
	<!ELEMENT min (#PCDATA)>
	<!ELEMENT stddev (#PCDATA)>
	<!ELEMENT average (#PCDATA)>
	<!ELEMENT count (#PCDATA)>
]>
<wcstats>
<site_wordcount>1643343993</site_wordcount>
<wordcounts>
<wcentry>
<wc>6764493</wc>
<wcdate>2008-11-01</wcdate>
<max>229641</max>
<min>0</min>
<stddev>3823</stddev>
<average>1612</average>
<count>4195</count>
</wcentry>
<wcentry>
<wc>52494309</wc>
<wcdate>2008-11-02</wcdate>
<max>268339</max>
<min>0</min>
<stddev>3687</stddev>
<average>2534</average>
<count>20708</count>
</wcentry>
<wcentry>
<wc>109450891</wc>
<wcdate>2008-11-03</wcdate>
<max>999999</max>
<min>0</min>
<stddev>6941</stddev>
<average>3612</average>
<count>30294</count>
</wcentry>
<wcentry>
<wc>171901148</wc>
<wcdate>2008-11-04</wcdate>
<max>999999</max>
<min>0</min>
<stddev>7517</stddev>
<average>4433</average>
<count>38777</count>
</wcentry>
<wcentry>
<wc>226762045</wc>
<wcdate>2008-11-05</wcdate>
<max>999999</max>
<min>0</min>
<stddev>8737</stddev>
<average>5189</average>
<count>43693</count>
</wcentry>
<wcentry>
<wc>281556390</wc>
<wcdate>2008-11-06</wcdate>
<max>999999</max>
<min>0</min>
<stddev>10678</stddev>
<average>5962</average>
<count>47224</count>
</wcentry>
<wcentry>
<wc>334965241</wc>
<wcdate>2008-11-07</wcdate>
<max>999999</max>
<min>0</min>
<stddev>12815</stddev>
<average>6732</average>
<count>49755</count>
</wcentry>
<wcentry>
<wc>380500176</wc>
<wcdate>2008-11-08</wcdate>
<max>999999</max>
<min>0</min>
<stddev>13462</stddev>
<average>7392</average>
<count>51468</count>
</wcentry>
<wcentry>
<wc>433464839</wc>
<wcdate>2008-11-09</wcdate>
<max>999999</max>
<min>0</min>
<stddev>14098</stddev>
<average>8185</average>
<count>52958</count>
</wcentry>
<wcentry>
<wc>491333222</wc>
<wcdate>2008-11-10</wcdate>
<max>999999</max>
<min>0</min>
<stddev>15000</stddev>
<average>9053</average>
<count>54268</count>
</wcentry>
<wcentry>
<wc>543352712</wc>
<wcdate>2008-11-11</wcdate>
<max>999999</max>
<min>0</min>
<stddev>14870</stddev>
<average>9789</average>
<count>55501</count>
</wcentry>
<wcentry>
<wc>596253558</wc>
<wcdate>2008-11-12</wcdate>
<max>999999</max>
<min>0</min>
<stddev>15658</stddev>
<average>10560</average>
<count>56463</count>
</wcentry>
<wcentry>
<wc>644216573</wc>
<wcdate>2008-11-13</wcdate>
<max>999999</max>
<min>0</min>
<stddev>16281</stddev>
<average>11264</average>
<count>57192</count>
</wcentry>
<wcentry>
<wc>689335026</wc>
<wcdate>2008-11-14</wcdate>
<max>999999</max>
<min>0</min>
<stddev>17321</stddev>
<average>11934</average>
<count>57758</count>
</wcentry>
<wcentry>
<wc>728240986</wc>
<wcdate>2008-11-15</wcdate>
<max>999999</max>
<min>0</min>
<stddev>17156</stddev>
<average>12509</average>
<count>58215</count>
</wcentry>
<wcentry>
<wc>780072043</wc>
<wcdate>2008-11-16</wcdate>
<max>999999</max>
<min>0</min>
<stddev>18454</stddev>
<average>13301</average>
<count>58647</count>
</wcentry>
<wcentry>
<wc>836640637</wc>
<wcdate>2008-11-17</wcdate>
<max>999999</max>
<min>0</min>
<stddev>18855</stddev>
<average>14141</average>
<count>59160</count>
</wcentry>
<wcentry>
<wc>885960031</wc>
<wcdate>2008-11-18</wcdate>
<max>999999</max>
<min>0</min>
<stddev>19456</stddev>
<average>14873</average>
<count>59566</count>
</wcentry>
<wcentry>
<wc>930596374</wc>
<wcdate>2008-11-19</wcdate>
<max>999999</max>
<min>0</min>
<stddev>20165</stddev>
<average>15539</average>
<count>59886</count>
</wcentry>
<wcentry>
<wc>976619532</wc>
<wcdate>2008-11-20</wcdate>
<max>999999</max>
<min>0</min>
<stddev>21497</stddev>
<average>16236</average>
<count>60151</count>
</wcentry>
<wcentry>
<wc>1017816556</wc>
<wcdate>2008-11-21</wcdate>
<max>999999</max>
<min>0</min>
<stddev>22163</stddev>
<average>16850</average>
<count>60401</count>
</wcentry>
<wcentry>
<wc>1055237435</wc>
<wcdate>2008-11-22</wcdate>
<max>999999</max>
<min>0</min>
<stddev>22342</stddev>
<average>17407</average>
<count>60620</count>
</wcentry>
<wcentry>
<wc>1103482184</wc>
<wcdate>2008-11-23</wcdate>
<max>999999</max>
<min>0</min>
<stddev>23388</stddev>
<average>18149</average>
<count>60801</count>
</wcentry>
<wcentry>
<wc>1158380457</wc>
<wcdate>2008-11-24</wcdate>
<max>999999</max>
<min>0</min>
<stddev>24288</stddev>
<average>18994</average>
<count>60986</count>
</wcentry>
<wcentry>
<wc>1217374975</wc>
<wcdate>2008-11-25</wcdate>
<max>999999</max>
<min>0</min>
<stddev>25552</stddev>
<average>19890</average>
<count>61205</count>
</wcentry>
<wcentry>
<wc>1272360653</wc>
<wcdate>2008-11-26</wcdate>
<max>999999</max>
<min>0</min>
<stddev>26472</stddev>
<average>20716</average>
<count>61419</count>
</wcentry>
<wcentry>
<wc>1322650718</wc>
<wcdate>2008-11-27</wcdate>
<max>999999</max>
<min>0</min>
<stddev>27064</stddev>
<average>21477</average>
<count>61582</count>
</wcentry>
<wcentry>
<wc>1367426987</wc>
<wcdate>2008-11-28</wcdate>
<max>999999</max>
<min>0</min>
<stddev>27949</stddev>
<average>22152</average>
<count>61727</count>
</wcentry>
<wcentry>
<wc>1429996336</wc>
<wcdate>2008-11-29</wcdate>
<max>999999</max>
<min>0</min>
<stddev>28954</stddev>
<average>23085</average>
<count>61943</count>
</wcentry>
<wcentry>
<wc>1643343993</wc>
<wcdate>2008-11-30</wcdate>
<max>999999</max>
<min>0</min>
<stddev>31313</stddev>
<average>26100</average>
<count>62963</count>
</wcentry>
</wordcounts>
</wcstats>
