<?xml version="1.0" standalone="yes"?><!DOCTYPE wchistory [
	<!ELEMENT wchistory (uid, error, uname, user_wordcount, wordcounts)>
	<!ELEMENT uid (#PCDATA)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT uname (#PCDATA)>
	<!ELEMENT user_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc,wcdate)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
]>
<wchistory>
<uid>240659</uid>
<uname>hollowedout</uname>
<user_wordcount>55415</user_wordcount>
<wordcounts>
<wcentry>
<wc>0</wc>
<wcdate>2008-11-01</wcdate>
</wcentry>
<wcentry>
<wc>2939</wc>
<wcdate>2008-11-02</wcdate>
</wcentry>
<wcentry>
<wc>5510</wc>
<wcdate>2008-11-03</wcdate>
</wcentry>
<wcentry>
<wc>8122</wc>
<wcdate>2008-11-04</wcdate>
</wcentry>
<wcentry>
<wc>8122</wc>
<wcdate>2008-11-05</wcdate>
</wcentry>
<wcentry>
<wc>8122</wc>
<wcdate>2008-11-06</wcdate>
</wcentry>
<wcentry>
<wc>14247</wc>
<wcdate>2008-11-07</wcdate>
</wcentry>
<wcentry>
<wc>16741</wc>
<wcdate>2008-11-08</wcdate>
</wcentry>
<wcentry>
<wc>16741</wc>
<wcdate>2008-11-09</wcdate>
</wcentry>
<wcentry>
<wc>20199</wc>
<wcdate>2008-11-10</wcdate>
</wcentry>
<wcentry>
<wc>21574</wc>
<wcdate>2008-11-11</wcdate>
</wcentry>
<wcentry>
<wc>21574</wc>
<wcdate>2008-11-12</wcdate>
</wcentry>
<wcentry>
<wc>24099</wc>
<wcdate>2008-11-13</wcdate>
</wcentry>
<wcentry>
<wc>26677</wc>
<wcdate>2008-11-14</wcdate>
</wcentry>
<wcentry>
<wc>26677</wc>
<wcdate>2008-11-15</wcdate>
</wcentry>
<wcentry>
<wc>26677</wc>
<wcdate>2008-11-16</wcdate>
</wcentry>
<wcentry>
<wc>26677</wc>
<wcdate>2008-11-17</wcdate>
</wcentry>
<wcentry>
<wc>32797</wc>
<wcdate>2008-11-18</wcdate>
</wcentry>
<wcentry>
<wc>32797</wc>
<wcdate>2008-11-19</wcdate>
</wcentry>
<wcentry>
<wc>33932</wc>
<wcdate>2008-11-20</wcdate>
</wcentry>
<wcentry>
<wc>35023</wc>
<wcdate>2008-11-21</wcdate>
</wcentry>
<wcentry>
<wc>40364</wc>
<wcdate>2008-11-22</wcdate>
</wcentry>
<wcentry>
<wc>40364</wc>
<wcdate>2008-11-23</wcdate>
</wcentry>
<wcentry>
<wc>42587</wc>
<wcdate>2008-11-24</wcdate>
</wcentry>
<wcentry>
<wc>42587</wc>
<wcdate>2008-11-25</wcdate>
</wcentry>
<wcentry>
<wc>45509</wc>
<wcdate>2008-11-26</wcdate>
</wcentry>
<wcentry>
<wc>45509</wc>
<wcdate>2008-11-27</wcdate>
</wcentry>
<wcentry>
<wc>47701</wc>
<wcdate>2008-11-28</wcdate>
</wcentry>
<wcentry>
<wc>53824</wc>
<wcdate>2008-11-29</wcdate>
</wcentry>
<wcentry>
<wc>55415</wc>
<wcdate>2008-11-30</wcdate>
</wcentry>
</wordcounts>
</wchistory>
