<?xml version="1.0" standalone="yes"?><!DOCTYPE wcregionhist [
	<!ELEMENT wcregionhist (rid, error, rname, region_wordcount, wordcounts)>
	<!ELEMENT rid (#PCDATA)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT rname (#PCDATA)>
	<!ELEMENT region_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc, wcdate, max, min, stddev, average, count, donations, numdonors)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
	<!ELEMENT max (#PCDATA)>
	<!ELEMENT min (#PCDATA)>
	<!ELEMENT stddev (#PCDATA)>
	<!ELEMENT average (#PCDATA)>
	<!ELEMENT count (#PCDATA)>
	<!ELEMENT donations (#PCDATA)>
	<!ELEMENT numdonors (#PCDATA)>
]>
<wcregionhist>
<rid>84</rid>
<rname>United States :: Washington :: Seattle</rname>
<region_wordcount>25865208</region_wordcount>
<wordcounts>
<wcentry>
<wc>71910</wc>
<wcdate>2008-11-01</wcdate>
<max>2883</max>
<min>62</min>
<stddev>0</stddev>
<average>1331</average>
<count>54</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>695248</wc>
<wcdate>2008-11-02</wcdate>
<max>11371</max>
<min>3</min>
<stddev>0</stddev>
<average>2653</average>
<count>262</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>1625778</wc>
<wcdate>2008-11-03</wcdate>
<max>27559</max>
<min>1</min>
<stddev>0</stddev>
<average>3908</average>
<count>416</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>2413589</wc>
<wcdate>2008-11-04</wcdate>
<max>31483</max>
<min>1</min>
<stddev>0</stddev>
<average>4723</average>
<count>511</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>3058448</wc>
<wcdate>2008-11-05</wcdate>
<max>39436</max>
<min>1</min>
<stddev>0</stddev>
<average>5510</average>
<count>555</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>3799629</wc>
<wcdate>2008-11-06</wcdate>
<max>44506</max>
<min>1</min>
<stddev>0</stddev>
<average>6364</average>
<count>597</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>4569130</wc>
<wcdate>2008-11-07</wcdate>
<max>50152</max>
<min>1</min>
<stddev>0</stddev>
<average>7287</average>
<count>627</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>5189194</wc>
<wcdate>2008-11-08</wcdate>
<max>50152</max>
<min>1</min>
<stddev>0</stddev>
<average>7971</average>
<count>651</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>5972666</wc>
<wcdate>2008-11-09</wcdate>
<max>52352</max>
<min>1</min>
<stddev>0</stddev>
<average>8901</average>
<count>671</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>6931977</wc>
<wcdate>2008-11-10</wcdate>
<max>52361</max>
<min>1</min>
<stddev>0</stddev>
<average>10149</average>
<count>683</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>7738454</wc>
<wcdate>2008-11-11</wcdate>
<max>52361</max>
<min>1</min>
<stddev>0</stddev>
<average>11054</average>
<count>700</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>8539085</wc>
<wcdate>2008-11-12</wcdate>
<max>57007</max>
<min>1</min>
<stddev>0</stddev>
<average>11976</average>
<count>713</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>9480351</wc>
<wcdate>2008-11-13</wcdate>
<max>66173</max>
<min>1</min>
<stddev>0</stddev>
<average>12916</average>
<count>734</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>10307820</wc>
<wcdate>2008-11-14</wcdate>
<max>70184</max>
<min>1</min>
<stddev>0</stddev>
<average>13891</average>
<count>742</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>10932630</wc>
<wcdate>2008-11-15</wcdate>
<max>73169</max>
<min>1</min>
<stddev>0</stddev>
<average>14635</average>
<count>747</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>11688373</wc>
<wcdate>2008-11-16</wcdate>
<max>80707</max>
<min>1</min>
<stddev>0</stddev>
<average>15481</average>
<count>755</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>12726851</wc>
<wcdate>2008-11-17</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>16658</average>
<count>764</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>13603369</wc>
<wcdate>2008-11-18</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>17643</average>
<count>771</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>14317821</wc>
<wcdate>2008-11-19</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>18546</average>
<count>772</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>14996255</wc>
<wcdate>2008-11-20</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>19275</average>
<count>778</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>15768048</wc>
<wcdate>2008-11-21</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>20112</average>
<count>784</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>16347455</wc>
<wcdate>2008-11-22</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>20719</average>
<count>789</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>17294403</wc>
<wcdate>2008-11-23</wcdate>
<max>123576</max>
<min>1</min>
<stddev>0</stddev>
<average>21836</average>
<count>792</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>18717055</wc>
<wcdate>2008-11-24</wcdate>
<max>297882</max>
<min>1</min>
<stddev>0</stddev>
<average>23484</average>
<count>797</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>19630108</wc>
<wcdate>2008-11-25</wcdate>
<max>297882</max>
<min>1</min>
<stddev>0</stddev>
<average>24537</average>
<count>800</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>20368005</wc>
<wcdate>2008-11-26</wcdate>
<max>297882</max>
<min>1</min>
<stddev>0</stddev>
<average>25428</average>
<count>801</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>21037606</wc>
<wcdate>2008-11-27</wcdate>
<max>297882</max>
<min>1</min>
<stddev>0</stddev>
<average>26166</average>
<count>804</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>21678457</wc>
<wcdate>2008-11-28</wcdate>
<max>297882</max>
<min>1</min>
<stddev>0</stddev>
<average>26896</average>
<count>806</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>22624700</wc>
<wcdate>2008-11-29</wcdate>
<max>297882</max>
<min>1</min>
<stddev>0</stddev>
<average>28035</average>
<count>807</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
<wcentry>
<wc>25865208</wc>
<wcdate>2008-11-30</wcdate>
<max>310458</max>
<min>1</min>
<stddev>0</stddev>
<average>31736</average>
<count>815</count>
<donations>7735.00</donations>
<donors></donors>
</wcentry>
</wordcounts>
</wcregionhist>
